import "./globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import React from "react";

import FooterComponent from "@/components/FooterComponent";
import Providers from "@/lib/Provider";

const montserratSans = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  display: "swap",
  variable: "--font-mont",
});
// оголошуються змінні для підключених шрифтів
// <body className={`${montserratSans.variable} antialiased`}> Додає змінні шрифтів

export const metadata: Metadata = {
  title: "Created by Fylypiv Volodymyr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratSans.variable} antialiased h-full flex flex-col min-h-screen`}>
        <Providers>{children}</Providers>
        <FooterComponent />
      </body>
    </html>
  );
}
